sudo: false
language: node_js
node_js:
- node
- lts/*
- '10'
deploy:
  provider: npm
  email:
    secure: hTPq0tl08Csq/hyTWNfzdO0JwSFluhm9HzYKuqpQfipRQV7K57Lbqb5yvJAB11gToJcItMwPjzs0zn5ySskGKiExJ9G3P9h8SDLBsqUIp/QqxUa9nzP5hQG8eHOP+qHVzq0TvRQDdtPeg1HgEzq7qHQHWMbBZ5wTjZPSHeQJKI9HfcopHd/6vDfoQ2hFHOnmnyAVXVzXBZpRR2aYebcr4SQEqQGtTavlbNo6u1A32XPv80yjZyGZWm9lMtySyEEqaepdP/IhAIr2+/S/uZi8MDwDMKMzxXMcdejfIgx26dJhMG9QMEcxViMIxpfMFDQuXSSMxO218up2m2/7axjESVkgk/d/wf8t8rcUnNVSIZ5g3QySKXZs+23BAkSCp/L9mO9vu4xEdU/UG3uBbpqV4Q9XOyp9ux7wpCJkgyoJE/RNnDRS2e0C2wA7LMHJ1qYK+4jQ4pNZkbpXDZT+NLX4OI77KBRbqoNRFK5id/nJBvGoSNQAPNah7h64GUl9NFr7D1DJnewAY2bCABedSA0TKp+2wiE3ffXrRQyOxKhymh8+fRNA4xkIabf16LLyC2Rm+8p1WITczlEmzJfWQ3WUIyyrBI+Xd6JtMeBuEy+2J5xPzxYxMLc6sFc96awETSxeZcv1oJ4LfD+F+2il5LhUr5mbiH1rEcZVUpYgfmnRgVw=
  api_key:
    secure: jLcg1B+EjWCc19w6QUtW4uVH9C6qG3R2paM/d70LP3FGEVivJ3LmUO/2sU2Eb7R3THW9Gke1W8RW6KAHtuw7iTrm48htHqfHAkOrQQYXZni9B8YnR7F2kKUKbumcOiR/SvFMAu+UgZAt1sl9iT7Btoht2VWOhQ1b3MNOBDgt+AQVKcbffMi7lJH4vO51hDYDTs0VcprcggR4G/jI7vCMDc6OOmaGokgqsle0pxF6ENShAaKOPgYAkP/pcMNnUdv85B3f6RcIonTWUS7+VbBIlMC6UgtxJqEUu87mvzxecAi0Bd2wHiJbTJQojopZkjcBi1CLSTm57meYWl3hC+8WdmP33+YjPhJ6Gy+4+11Yky29fLYoUChzDOhAwT4idKXU4OSQktLCEwuGS7zvqM0LhVH/bR+5XJepKkgT/76QBIWr3VBeDsHCa5rp8yyWn1P5LCU5+ZMs6kmn3Ywv30N0osg5nl7WEE4RiM7WZADfDLsRefU7WtK+ObIP8k1htdoB8Ge77UazylnFDN9UICOWSNlwdcYbLxhHgn2Hy7+fPirtaDu04W/9p99qodPuPYN3+dRzWNPNdH6m2hrOdlGq8xYR8Z2aWP1de5QOYnrseDmzkSoWtQFE6wCK8h0Ho2zYNH2v9EDLnnR6beWLThBjvnOxYvks63rClSxWri0U4J4=
  on:
    tags: true
